jobs:
  build:
    runs-on: ubuntu-latest

    services:
      cockroachdb:
        image: cockroachdb/cockroach:v21.1.8
        ports:
          - 26257:26257
        options: --insecure start-single-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven install
        run: mvn clean install

      - name: Run tests
        run: mvn clean test
